# .github/workflows/flutter-web-build.yml
name: Flutter Web Build

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v3

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.19.0' # change to your required version

      - name: Install dependencies
        run: flutter pub get

      - name: Build Flutter web
        run: flutter build web

      - name: Upload build output as artifact
        uses: actions/upload-artifact@v3
        with:
          name: flutter-web-build
          path: build/web
