
name: flutter-web-build
 
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          flutter-version: 3.24.4
      - run: flutter --version
      - run: flutter pub get
      - run: flutter test
      - run: flutter build web
      - name: Upload build output as artifact
        uses: actions/upload-artifact@v3
        with:
          name: flutter-web-build
          path: build/web